language: go

go:
    - 1.8

sudo: required
services:
  - docker

before_script:
  - go get github.com/chespinoza/goliscan
  
script:
  - make check-license
  - make check-vendor-licenses
  - make docker_up coverage

notifications:
    slack: thingful:1X9OpFzHUf1i7Y9lPyHoNGld
