language: go

go:
    - 1.8

sudo: required
services:
  - docker

before_script:
  - make get-build-deps

script:
  - make check-license
  - make check-vendor-licenses
  - make proto-verify
  - make docker-up
  - make coverage

notifications:
    slack: thingful:1X9OpFzHUf1i7Y9lPyHoNGld
