// Code generated by protoc-gen-go.
// source: devicehub.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	devicehub.proto

It has these top-level messages:
	PipeDeleteRequest
	PipeDeleteReply
	PipeListRequest
	PipeListReply
	Pipe
	Endpoint
	Profile
	Statistics
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type PipeState int32

const (
	PipeState_UNKNOWN PipeState = 0
	PipeState_RUNNING PipeState = 1
	PipeState_STOPPED PipeState = 2
	PipeState_ERRORED PipeState = 3
)

var PipeState_name = map[int32]string{
	0: "UNKNOWN",
	1: "RUNNING",
	2: "STOPPED",
	3: "ERRORED",
}
var PipeState_value = map[string]int32{
	"UNKNOWN": 0,
	"RUNNING": 1,
	"STOPPED": 2,
	"ERRORED": 3,
}

func (x PipeState) String() string {
	return proto1.EnumName(PipeState_name, int32(x))
}
func (PipeState) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type PipeDeleteRequest struct {
	Uri string `protobuf:"bytes,1,opt,name=uri" json:"uri,omitempty"`
}

func (m *PipeDeleteRequest) Reset()                    { *m = PipeDeleteRequest{} }
func (m *PipeDeleteRequest) String() string            { return proto1.CompactTextString(m) }
func (*PipeDeleteRequest) ProtoMessage()               {}
func (*PipeDeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PipeDeleteRequest) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

type PipeDeleteReply struct {
	Ok bool `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
}

func (m *PipeDeleteReply) Reset()                    { *m = PipeDeleteReply{} }
func (m *PipeDeleteReply) String() string            { return proto1.CompactTextString(m) }
func (*PipeDeleteReply) ProtoMessage()               {}
func (*PipeDeleteReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PipeDeleteReply) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type PipeListRequest struct {
}

func (m *PipeListRequest) Reset()                    { *m = PipeListRequest{} }
func (m *PipeListRequest) String() string            { return proto1.CompactTextString(m) }
func (*PipeListRequest) ProtoMessage()               {}
func (*PipeListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type PipeListReply struct {
	Pipes []*Pipe `protobuf:"bytes,1,rep,name=pipes" json:"pipes,omitempty"`
}

func (m *PipeListReply) Reset()                    { *m = PipeListReply{} }
func (m *PipeListReply) String() string            { return proto1.CompactTextString(m) }
func (*PipeListReply) ProtoMessage()               {}
func (*PipeListReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PipeListReply) GetPipes() []*Pipe {
	if m != nil {
		return m.Pipes
	}
	return nil
}

type Pipe struct {
	Uri string `protobuf:"bytes,1,opt,name=uri" json:"uri,omitempty"`
	// TODO : reinstate
	// google.protobuf.Timestamp started = 2;
	State        PipeState   `protobuf:"varint,2,opt,name=state,enum=proto.PipeState" json:"state,omitempty"`
	Profile      *Profile    `protobuf:"bytes,3,opt,name=profile" json:"profile,omitempty"`
	Listener     *Endpoint   `protobuf:"bytes,4,opt,name=listener" json:"listener,omitempty"`
	MessageStats *Statistics `protobuf:"bytes,5,opt,name=message_stats,json=messageStats" json:"message_stats,omitempty"`
	Endpoints    []*Endpoint `protobuf:"bytes,6,rep,name=endpoints" json:"endpoints,omitempty"`
}

func (m *Pipe) Reset()                    { *m = Pipe{} }
func (m *Pipe) String() string            { return proto1.CompactTextString(m) }
func (*Pipe) ProtoMessage()               {}
func (*Pipe) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Pipe) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *Pipe) GetState() PipeState {
	if m != nil {
		return m.State
	}
	return PipeState_UNKNOWN
}

func (m *Pipe) GetProfile() *Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func (m *Pipe) GetListener() *Endpoint {
	if m != nil {
		return m.Listener
	}
	return nil
}

func (m *Pipe) GetMessageStats() *Statistics {
	if m != nil {
		return m.MessageStats
	}
	return nil
}

func (m *Pipe) GetEndpoints() []*Endpoint {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

type Endpoint struct {
	Uid  string `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
	Type string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
}

func (m *Endpoint) Reset()                    { *m = Endpoint{} }
func (m *Endpoint) String() string            { return proto1.CompactTextString(m) }
func (*Endpoint) ProtoMessage()               {}
func (*Endpoint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Endpoint) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *Endpoint) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type Profile struct {
	Name        string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Version     string `protobuf:"bytes,3,opt,name=version" json:"version,omitempty"`
}

func (m *Profile) Reset()                    { *m = Profile{} }
func (m *Profile) String() string            { return proto1.CompactTextString(m) }
func (*Profile) ProtoMessage()               {}
func (*Profile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Profile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Profile) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Profile) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type Statistics struct {
	Total  uint64 `protobuf:"varint,1,opt,name=total" json:"total,omitempty"`
	Errors uint64 `protobuf:"varint,2,opt,name=errors" json:"errors,omitempty"`
	Ok     uint64 `protobuf:"varint,3,opt,name=ok" json:"ok,omitempty"`
}

func (m *Statistics) Reset()                    { *m = Statistics{} }
func (m *Statistics) String() string            { return proto1.CompactTextString(m) }
func (*Statistics) ProtoMessage()               {}
func (*Statistics) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Statistics) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Statistics) GetErrors() uint64 {
	if m != nil {
		return m.Errors
	}
	return 0
}

func (m *Statistics) GetOk() uint64 {
	if m != nil {
		return m.Ok
	}
	return 0
}

func init() {
	proto1.RegisterType((*PipeDeleteRequest)(nil), "proto.PipeDeleteRequest")
	proto1.RegisterType((*PipeDeleteReply)(nil), "proto.PipeDeleteReply")
	proto1.RegisterType((*PipeListRequest)(nil), "proto.PipeListRequest")
	proto1.RegisterType((*PipeListReply)(nil), "proto.PipeListReply")
	proto1.RegisterType((*Pipe)(nil), "proto.Pipe")
	proto1.RegisterType((*Endpoint)(nil), "proto.Endpoint")
	proto1.RegisterType((*Profile)(nil), "proto.Profile")
	proto1.RegisterType((*Statistics)(nil), "proto.Statistics")
	proto1.RegisterEnum("proto.PipeState", PipeState_name, PipeState_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Hub service

type HubClient interface {
	// delete pipe by URI
	PipeDelete(ctx context.Context, in *PipeDeleteRequest, opts ...grpc.CallOption) (*PipeDeleteReply, error)
	// list all running pipes
	PipeList(ctx context.Context, in *PipeListRequest, opts ...grpc.CallOption) (*PipeListReply, error)
}

type hubClient struct {
	cc *grpc.ClientConn
}

func NewHubClient(cc *grpc.ClientConn) HubClient {
	return &hubClient{cc}
}

func (c *hubClient) PipeDelete(ctx context.Context, in *PipeDeleteRequest, opts ...grpc.CallOption) (*PipeDeleteReply, error) {
	out := new(PipeDeleteReply)
	err := grpc.Invoke(ctx, "/proto.Hub/PipeDelete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubClient) PipeList(ctx context.Context, in *PipeListRequest, opts ...grpc.CallOption) (*PipeListReply, error) {
	out := new(PipeListReply)
	err := grpc.Invoke(ctx, "/proto.Hub/PipeList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Hub service

type HubServer interface {
	// delete pipe by URI
	PipeDelete(context.Context, *PipeDeleteRequest) (*PipeDeleteReply, error)
	// list all running pipes
	PipeList(context.Context, *PipeListRequest) (*PipeListReply, error)
}

func RegisterHubServer(s *grpc.Server, srv HubServer) {
	s.RegisterService(&_Hub_serviceDesc, srv)
}

func _Hub_PipeDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PipeDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServer).PipeDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Hub/PipeDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServer).PipeDelete(ctx, req.(*PipeDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hub_PipeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PipeListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServer).PipeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Hub/PipeList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServer).PipeList(ctx, req.(*PipeListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Hub_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Hub",
	HandlerType: (*HubServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PipeDelete",
			Handler:    _Hub_PipeDelete_Handler,
		},
		{
			MethodName: "PipeList",
			Handler:    _Hub_PipeList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "devicehub.proto",
}

func init() { proto1.RegisterFile("devicehub.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 497 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x53, 0xcd, 0x6f, 0xd3, 0x30,
	0x14, 0x5f, 0x9a, 0x7e, 0xbe, 0xb2, 0x36, 0xb5, 0xc6, 0x14, 0xed, 0xd4, 0x45, 0x02, 0x15, 0x10,
	0x15, 0x0a, 0x12, 0x07, 0x2e, 0xa0, 0xa9, 0x15, 0xe3, 0x43, 0x69, 0xe4, 0x31, 0x21, 0x4e, 0xa8,
	0x6d, 0xde, 0x36, 0xab, 0x59, 0x6c, 0x62, 0x67, 0x52, 0xcf, 0xfc, 0xdf, 0x08, 0xd9, 0x71, 0xda,
	0xa0, 0xee, 0xd4, 0xf7, 0xfb, 0x7a, 0xb6, 0x5f, 0x5f, 0x60, 0x98, 0xe0, 0x03, 0x5b, 0xe3, 0x5d,
	0xb1, 0x9a, 0x8a, 0x9c, 0x2b, 0x4e, 0x5a, 0xe6, 0x27, 0x78, 0x06, 0xa3, 0x98, 0x09, 0x9c, 0x61,
	0x8a, 0x0a, 0x29, 0xfe, 0x2e, 0x50, 0x2a, 0xe2, 0x81, 0x5b, 0xe4, 0xcc, 0x77, 0xc6, 0xce, 0xa4,
	0x47, 0x75, 0x19, 0x9c, 0xc3, 0xb0, 0x6e, 0x13, 0xe9, 0x96, 0x0c, 0xa0, 0xc1, 0x37, 0xc6, 0xd3,
	0xa5, 0x0d, 0xbe, 0x09, 0x46, 0xa5, 0xe5, 0x1b, 0x93, 0xca, 0xf6, 0x09, 0x42, 0x38, 0xde, 0x53,
	0x3a, 0x73, 0x0e, 0x2d, 0xc1, 0x04, 0x4a, 0xdf, 0x19, 0xbb, 0x93, 0x7e, 0xd8, 0x2f, 0xef, 0x32,
	0xd5, 0x26, 0x5a, 0x2a, 0xc1, 0x5f, 0x07, 0x9a, 0x1a, 0x1f, 0x5e, 0x82, 0x3c, 0x87, 0x96, 0x54,
	0x4b, 0x85, 0x7e, 0x63, 0xec, 0x4c, 0x06, 0xa1, 0x57, 0x4b, 0x5f, 0x69, 0x9e, 0x96, 0x32, 0x99,
	0x40, 0x47, 0xe4, 0xfc, 0x86, 0xa5, 0xe8, 0xbb, 0x63, 0x67, 0xd2, 0x0f, 0x07, 0x95, 0xb3, 0x64,
	0x69, 0x25, 0x93, 0x57, 0xd0, 0x4d, 0x99, 0x54, 0x98, 0x61, 0xee, 0x37, 0x8d, 0x75, 0x68, 0xad,
	0xf3, 0x2c, 0x11, 0x9c, 0x65, 0x8a, 0xee, 0x0c, 0xe4, 0x1d, 0x1c, 0xdf, 0xa3, 0x94, 0xcb, 0x5b,
	0xfc, 0xa5, 0xcf, 0x91, 0x7e, 0xcb, 0x24, 0x46, 0x36, 0xa1, 0xaf, 0xc0, 0xa4, 0x62, 0x6b, 0x49,
	0x9f, 0x58, 0x9f, 0xa6, 0x24, 0x79, 0x0d, 0x3d, 0xb4, 0xdd, 0xa4, 0xdf, 0x36, 0x0f, 0x3f, 0x38,
	0x65, 0xef, 0x08, 0xde, 0x40, 0xb7, 0xa2, 0xcd, 0x0c, 0x58, 0xb2, 0x9b, 0x01, 0x4b, 0x08, 0x81,
	0xa6, 0xda, 0x8a, 0x72, 0x04, 0x3d, 0x6a, 0xea, 0xe0, 0x27, 0x74, 0xec, 0xcb, 0xb4, 0x9c, 0x2d,
	0xef, 0xd1, 0x26, 0x4c, 0x4d, 0xc6, 0xd0, 0x4f, 0x50, 0xae, 0x73, 0x26, 0x14, 0xe3, 0x99, 0x4d,
	0xd6, 0x29, 0xe2, 0x43, 0xe7, 0x01, 0x73, 0xa9, 0x55, 0xd7, 0xa8, 0x15, 0x0c, 0xbe, 0x00, 0xec,
	0xdf, 0x45, 0x4e, 0xa0, 0xa5, 0xb8, 0x5a, 0xa6, 0xa6, 0x7d, 0x93, 0x96, 0x80, 0x9c, 0x42, 0x1b,
	0xf3, 0x9c, 0xe7, 0xd2, 0xb4, 0x6e, 0x52, 0x8b, 0xec, 0x82, 0xb8, 0x86, 0x6b, 0xf0, 0xcd, 0xcb,
	0x0f, 0xd0, 0xdb, 0xfd, 0x55, 0xa4, 0x0f, 0x9d, 0xeb, 0xe8, 0x6b, 0xb4, 0xf8, 0x11, 0x79, 0x47,
	0x1a, 0xd0, 0xeb, 0x28, 0xfa, 0x1c, 0x7d, 0xf2, 0x1c, 0x0d, 0xae, 0xbe, 0x2f, 0xe2, 0x78, 0x3e,
	0xf3, 0x1a, 0x1a, 0xcc, 0x29, 0x5d, 0xd0, 0xf9, 0xcc, 0x73, 0xc3, 0x3f, 0x0e, 0xb8, 0x97, 0xc5,
	0x8a, 0x7c, 0x04, 0xd8, 0x2f, 0x23, 0xf1, 0x6b, 0x6b, 0xf0, 0xdf, 0x1a, 0x9f, 0x9d, 0x3e, 0xa2,
	0x88, 0x74, 0x1b, 0x1c, 0x91, 0xf7, 0xd0, 0xad, 0x16, 0x93, 0xd4, 0x5d, 0xb5, 0xe5, 0x3d, 0x3b,
	0x39, 0xe0, 0x4d, 0xf6, 0xe2, 0x05, 0x3c, 0x65, 0x7c, 0xaa, 0xee, 0x58, 0x76, 0x7b, 0x53, 0xa4,
	0xd3, 0xdd, 0x77, 0x75, 0x31, 0x98, 0x99, 0xf2, 0xb2, 0x58, 0xc5, 0x3a, 0x18, 0x3b, 0xab, 0xb6,
	0xe9, 0xf0, 0xf6, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf7, 0x2b, 0xae, 0x14, 0x7d, 0x03, 0x00,
	0x00,
}
